### ISSUE TITLE
Unexpected error while processing request

### ISSUE THREAD

**Issue by IslamAzab** [phallguy/shog#11]
!! Unexpected error while processing request: no implicit conversion of Hash into String

**Comment by phallguy** [comment]
Hi @IslamAzab, thanks for your interest in Shog. I'm afraid I can't really do much with your issue report though. Can you provide some more context? An example? Full stack trace?

**Comment by IslamAzab** [comment]
@phallguy Thanks for your reply.

Hmmmm I just added it to the gem file, and followed the instructions for its setup, however with each request that's what I only get, which is very weird I couldn't even debug it.

**Comment by phallguy** [comment]
Unfortunately I'll need more than that to really offer any help. Can you attach a full stack trace?

**Comment by IslamAzab** [comment]
@phallguy Thanks for trying to help. I just added the gem to the "development" group and it worked. I didn't add the initializer too.

**Comment by IslamAzab** [comment]
I wasn't able to make it work with `zeus`, I kept getting the same message only `!! Unexpected error while processing request: no implicit conversion of Hash into String`
