### ISSUE TITLE
rails 5 (rack 2.0) support

### ISSUE THREAD

**Issue by jakoss** [phallguy/shog#12]
Any plans for rack 2.0 support?

**Comment by phallguy** [comment]
Haven't looked at rails 5 yet - personal projects have too many dependencies on 4.x line of stuff to move over year. The library is pretty modular and shouldn't take to much to change if there are any changes needed. I'd welcome a PR but probably won't be looking hard at supporting rack 2/rails 5 until their stable releases.

**Comment by jakoss** [comment]
Here you go #13
