### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by ybart** [phallguy/shog#2]
I got the following error while updating to Rails 4.2. The error didn't occur in development, but with the production environment (using Heroku). Here is the relevant stack trace :

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       NoMethodError: undefined method `configure' for #<ActiveSupport::Logger::SimpleFormatter:0x007f18f33e0338>
       /tmp/build_92a62613341d2c260074de0bba6d743b/vendor/bundle/ruby/2.2.0/gems/shog-0.1.3/lib/shog.rb:12:in `configure'
       /tmp/build_92a62613341d2c260074de0bba6d743b/config/initializers/shog.rb:1:in `<top (required)>'
```

It looks like something prevents the Shog Railtie from doing its job. It might be a configuration problem however.

In the meantime I successfully changed my initialiser to:

``` ruby
::Rails.logger.formatter = Shog::Formatter.new.configure do
  reset_config!
  ...
end
```

Any other report for Shog with Rails 4.2 ?

**Comment by phallguy** [comment]
Thanks ybart! If you'd like to take a look at it I'd welcome a PR. But I'll dig into it as well to see if I can figure out what the problem is.

**Comment by ybart** [comment]
Here are the results of my investigations.

The Railtie sets the logger formatter appropriately to an instance of Shog::Formatter as expected The job is done as expected before initializers are called. But in the initializer, the rails logger formatter has been replaced by an instance of SimpleFormatter.

I found out that the culprit is in fact rails_stdout_logging (which replaces the file logger with stdout logger) which resets the logger after shog set its formatter. So, it's not related to the Rails 4.2 update at all but to the Heroku setup.

```
#<Proc:0x007fa72a4cfe40@$HOME/.rvm/gems/ruby-2.2.0/gems/rails_stdout_logging-0.0.3/lib/rails_stdout_logging/railtie.rb:5>
```

Since it's not really a problem in Shog but rather a conflict between another gem, an update in the README indicating that rails_stdout_logging should always use an initializer with my syntax is probably sufficient.

But I will send a pull request with a workaround for this.
