### ISSUE TITLE
How change the text color of [INFO] ?

### ISSUE THREAD

**Issue by edudepetris** [phallguy/shog#8]
My terminal colours configuration + shog aren't  work well! 

The  text is missing  by the color.
![screen shot 2015-07-11 at 2 32 33 pm](https://cloud.githubusercontent.com/assets/2192588/8634707/3d5ae468-27da-11e5-85b6-f47bca4b7996.png)

How can I change this color ? 

BTW: Good gem, good job!

**Comment by phallguy** [comment]
All the colors are defined by formatters, the defaults defined in [formatters/defaults.rb](https://github.com/phallguy/shog/blob/master/lib/shog/formatters/defaults.rb)

If you wanted to customize the colors you can just make your own formatter when configuring shog. Something like this:

``` ruby
Shog.configure do
  severity( :info ){ msg.yellow }
end
```

**Comment by valtterimaja** [comment]
I don't think this is a good default. According to this poll, most people use a dark terminal background.

https://opensource.com/life/14/9/what-color-terminal-background
